apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-properties
  namespace: logging
data:
    fluent-bit.conf: |
      [SERVICE]
        # Hizmet ayarları
        Flush        1
        Log_Level    info
        Daemon       off
        Parsers_File parsers.conf # Parsers dosyasını dahil et
      [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
      [OUTPUT]
        Name  stdout
        Match *